### ISSUE TITLE
Munca pt maine

### ISSUE THREAD

**Issue by Cr-N** [Cr-N/Ftc-off-season-Bit-Mo#16]
##To Do List

- [x] Testare senzor culoare (colorSensorTesting.java in folder Tests din Teamcode)
- [x] Testare Drive_Arm_Rotate.java in folder TeleOps _Testare mai maulte subsystem-uri, va rog faceti un code review **pls** sper sa nu sparg intake-ul cu codu _.
- [x] Tunare variabile de detectie pixeli pt senzor de culoare si distanta
- [x] Finalizare Subsystemuri Arm,Rotate,Intake,DriveBase,ColorSensor
- [ ] Inceput Tuning?

**Comment by Iuli1234** [comment]
💪
